config/routes.rb
Rails.application.routes.draw do
  post "/create_user", to: "users#create", as: "create_user"

  devise_for :users
  root to: "pages#home"
  get 'pages/terminos_de_uso', to: "pages#terminos_de_uso", as: "terminos_de_uso"
  get 'users/:id', to: 'users#show', as: :user
  get 'profile', to: 'users#profile', as: :profile
  resources :items, except: [:destroy] do
    member do
      patch :hide
    end
  end
  get 'myitems', to: 'items#my_items', as: :myitems

    resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
end
  resources :offers, only: [:new, :show, :create, :edit, :update, :destroy] do
    member do
      patch :reject
      patch :cancel
    end
  end
  resources :deals, only: [:index, :show, :create] do
    member do
      patch :cancel
      patch :complete
    end
    resources :reviews, only: [:create]

  end
  resources :chatrooms, only: [:index, :show, :create] do
    resources :messages, only: :create
  end
  resources :preferences, only: [:create, :destroy]

  # resources :users, only: [:create]
end

app/views/shared/_banner.html.erb
<div class="banner index-banner">
  <div class="container">
    <h1>Convierte lo que tienes en lo que deseas</h1>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mobile-only p-0 m-0 bg-white">
  <div class="footer-links w-100 h-100 d-flex align-items-center justify-content-around">
    <%= link_to deals_path, class: 'footer-link' do %>
      <div class="text-secondary">
        <i class="w-100 text-center fa-solid fa-rotate"></i>
        <% if !user_signed_in? || current_user.received_offers.where(status: 'pending').empty? %>
          <p class="m-0 fs-6 text-center">Mis trueques</p>
        <% else %>
          <p class="m-0 fs-6 text-center">Mis trueques <i class="fa-solid fa-bell"></i></p>
        <% end %>
      </div>
    <% end %>
        <%= link_to chatrooms_path, class: 'footer-link' do %>
          <div class="text-secondary">
            <i class="w-100 text-center fa-solid fa-message"></i>
            <% if !user_signed_in? || !Message.where.not(user: current_user).where(read: false, chatroom: current_user.chatrooms).any? %>
              <p class="m-0 fs-6 text-center">Chats <i class="fa-solid fa-envelope-open"></i></p>
            <% else %>
              <p class="m-0 fs-6 text-center">Chats <i class="fa-regular fa-envelope"></i></p>
            <% end %>
            </div class="text-secondary">
          <% end %>
          <%= link_to new_item_path, class: 'footer-link' do %>
          <div class="text-secondary">
            <i class="w-100 fs-1 text-center fa-solid fa-circle-plus"></i>
          </div>
        <% end %>
        <%= link_to items_path, class: 'footer-link' do %>
          <div class="text-secondary">
            <i class="w-100 text-center fa-solid fa-globe"></i>
            <p class="m-0 fs-6 text-center">Explora</p>
          </div>
        <% end %>
        <%= link_to myitems_path, class: 'footer-link' do %>
          <div class="text-secondary">
            <i class="w-100 text-center fa-solid fa-rectangle-list"></i>
            <p class="m-0 fs-6 text-center">Mis ofertas</p>
          </div>
        <% end %>
      </div>
    </div>


<div class="footer border-top desktop-only mt-4">
  <div class="footer-copyright">
   <p><em>© 2024 Loop</em></p>
   <%= link_to 'Términos de uso', terminos_de_uso_path %>
  </div>

  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light sticky-top p-0">
  <div class="d-flex flex-column w-100">
    <div class="gray-background-color">
  <div class="w-100 d-flex justify-content-between p-2 pt-4">
      <%= link_to "/", class: "navbar-brand d-flex align-items-center px-4" do %>
        <%= image_tag "Loop.png", class: "me-3" %>
      <% end %>
    <% unless current_page? root_path %>
      <div class="wrapper desktop-only">
        <div class="search">
          <%= render "shared/search" %>
        </div>
      </div>
    <% end %>

    <ul class="navbar-nav">
      <li class="nav-item d-none d-md-block">
        <% if user_signed_in? %>
          <p class="mx-2"><strong><%= current_user.nickname %></strong></p>
        <% end %>
      </li>
      <li class="nav-item dropdown position-relative">
        <%= render "shared/navbar/avatar" %>
      </li>
    </ul>
  </div>
  </div>
  <% unless current_page?(items_path) || current_page?(root_path) %>
    <%= link_to :back, class: 'h2 text-primary-darker align-self-start' do %>
      <i class="fa-solid fa-arrow-left ps-3 pt-3"></i>
    <%end%>
  <%end%>
  </div>
</div>

app/views/shared/_qrcode.html.erb
<div class='m-5 p-5 text-center'>
  <div class='border-purple p-5'>
    <%= image_tag "Loop.png", class: "mb-3", style: "max-width: 200px;" %>
    <div class='mt-5'><%= raw app_qr_code_url %></div>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="row justify-content-center">
    <%= form_with url: items_path, method: :get, class: "d-flex form-inline px-0 gap-2" do %>
        <%= select_tag :category,
          options_for_select(Category.all.map { |c| [c.name, c.id] }),
          include_blank: "Categoría",
          class: "form-control rounded bg-primary border-primary-darker"
        %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control rounded bg-primary border-primary-darker",
            placeholder: "Buscar"
        %>
        <%= text_field_tag :location,
            params[:location],
            class: "form-control rounded bg-primary border-primary-darker desktop-only",
            placeholder: "Ubicación"
        %>
        <button type="submit" class="btn border-0 m-0 flex-shrink-1 btn-search" title="Search">
          <i class="fas fa-search"></i>
        </button>
    <% end %>
</div>