config/routes.rb
Rails.application.routes.draw do
  post "/create_user", to: "users#create", as: "create_user"

  devise_for :users
  root to: "pages#home"
  get 'pages/terminos_de_uso', to: "pages#terminos_de_uso", as: "terminos_de_uso"
  get 'users/:id', to: 'users#show', as: :user
  get 'profile', to: 'users#profile', as: :profile
  resources :items, except: [:destroy] do
    member do
      patch :hide
    end
  end
  get 'myitems', to: 'items#my_items', as: :myitems

    resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
end
  resources :offers, only: [:new, :show, :create, :edit, :update, :destroy] do
    member do
      patch :reject
      patch :cancel
    end
  end
  resources :deals, only: [:index, :show, :create] do
    member do
      patch :cancel
      patch :complete
    end
    resources :reviews, only: [:create]

  end
  resources :chatrooms, only: [:index, :show, :create] do
    resources :messages, only: :create
  end
  resources :preferences, only: [:create, :destroy]

  # resources :users, only: [:create]
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :offer
  has_many :reviews
  delegate :requested_item, to: :offer
  delegate :offered_item, to: :offer
  delegate :user_requested, to: :offer
  delegate :user_offerer, to: :offer

  def users
    [user_requested, user_offerer]
  end

  def items
    offered_items.or(Item.where(id: requested_item))
  end

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: %i[show cancel complete]

  def index
    @offered_offers = current_user.offered_offers.where(status: 'pending')
    @received_offers = current_user.received_offers.where(status: 'pending')
    @deals = current_user.deals
    @deal = Deal.new
    @review = Review.new
    @chatroom = Chatroom.new
    @accepted_deals = filter_deals('accepted')
    @completed_deals = filter_deals('completed')
    @canceled_deals = filter_deals('canceled')
    @finished_deals = @completed_deals + @canceled_deals
  end

  def show
    @reviewed_user = @deal.user_offerer == current_user ? @deal.user_requested : @deal.user_offerer
    @reviews = Review.where(user_reviewed: @reviewed_user)
    @rating = @reviews.average(:rating).round(2) if @reviews.any?
    @review = Review.new
    @chatroom = Chatroom.new
    authorize @deal
  end

  def create
    @deal = Deal.new(deal_params)
    @deal.status = "accepted"
    if @deal.save
      Offer.find(@deal.offer_id).update(status: "accepted")
      redirect_to deals_path, notice: "Trueque aceptado"
    else
      render 'deals/index'
    end
  end

  def cancel
    @deal.status = "canceled"
    @deal.save
    redirect_to deals_path
  end

  def complete
    @deal.status = "completed"
    @deal.save
    # Hide items after a deal is completed
    @items = [@deal.offered_item, @deal.requested_item]
    @items.each do |item|
      if item.category.name != "Servicios"
        item.update(hidden: true)
        # Cancel offers related to an item that's hidden after a deal is completed
        offers = Offer.where(offered_item: item)
        offers.update_all(status: "canceled") if offers.any?

        requests = Offer.where(requested_item: item)
        requests.update_all(status: "canceled") if requests.any?

        # Cancel deals related to an item that's hidden after a deal is completed
        deals = Deal.joins(:offer).where.not(status: 'completed').where("offers.offered_item_id = ? OR offers.requested_item_id = ?", item.id, item.id)
        deals.update_all(status: "canceled") if deals.any?
      end
    end
    redirect_to deals_path
  end


  private

  def deal_params
  params.require(:deal).permit(:offer_id)
  end

  def set_deal
    @deal = Deal.find(params[:id])
  end

  def filter_deals(status)
    @deals.select { |deal| deal.status == status }
  end

end

app/views/deals/_accept_offer.html.erb
      <%= simple_form_for(deal) do |f| %>
        <%= f.hidden_field :offer_id, value: offer.id %>
        <%= f.button :submit, "Aceptar", class: 'btn btn-primary-dark border-primary-darker my-2' %>
      <% end %>

app/views/deals/_cancel.html.erb
      <%= simple_form_for(deal, url: cancel_deal_path(deal), method: :patch) do |f| %>
        <div class="text-center">
          <%= f.button :submit, "Cancelar Trueque", class: 'btn btn-danger my-2' %>
        </div>
      <% end %>

app/views/deals/_cancel_offer.html.erb
<%= simple_form_for(offer, url: reject_offer_path(offer), method: :patch) do |f| %>
          <div class="text-center">
          <%= f.button :submit, "Cancelar Oferta", class: 'btn btn-outline-danger' %>
          </div>
        <% end %>

app/views/deals/_canceled_deals.html.erb
<h4 class='text-center my-2'>Cancelados (<%= canceled_deals.count %>) <i class="fa-solid fa-circle-chevron-up" data-action='click->display-deals#canceled' data-display-deals-target='chevroncanceled'></i></h4>
<div class='my-2 d-none' data-display-deals-target='canceleddeal'>
  <% @canceled_deals.each do |deal| %>
  <div class='my-2 bg-primary'>
    <%= render 'deals/dealstatus', deal: deal %>
  </div>
  <% end %>
</div>

app/views/deals/_cards.html.erb
<% exchanges.each do |exchange| %>
  <div class='deal-card align-self-start d-flex flex-column justify-content-between rounded-4 shadow my-2 bg-primary'>
    <div class="ps-3" style="height: 20px; font-size: 15px;">
    <% if exchange.status == 'completed' %>
      <span class="text-success fw-bold"> Concluido </span>
    <% elsif exchange.status == 'canceled' %>
      <span class="text-danger fw-bold"> Cancelado </span>
    <% elsif exchange.status == 'pending' %>
      <% if exchange.user_requested == current_user %>
        <%offerer_name = exchange.user_offerer.nickname.nil? ? exchange.user_offerer.email.split("@").first : exchange.user_offerer.nickname %>
        <span><%= "#{offerer_name} te envio una oferta!" %></span>
      <% else %>
        <%user_requested_name = exchange.user_requested.nickname.nil? ? exchange.user_requested.email.split("@").first : exchange.user_requested.nickname %>
        <span><%= "Oferta enviada!" %></span>
      <% end %>
    <% else %>
      <span class="text-warning fw-bold"> Pendiente </span>
    <% end %>
    </div>
    <%= render 'deals/status', exchange: exchange %>
    <div class="d-flex justify-content-around align-items-center w-100 flex-grow-1">
    <% if exchange.status == 'accepted' %>
      <%= render 'deals/cancel', deal: exchange %>
      <%= render 'deals/complete', deal: exchange %>
    <% elsif exchange.status == 'pending' %>
      <% if exchange.user_requested == current_user %>
        <%= render 'deals/reject_offer', deal: @deal, offer: exchange%>
        <%= render 'deals/accept_offer', deal: @deal, offer: exchange%>
      <% else %>
        <%= render 'deals/cancel_offer', offer: exchange %>
      <% end %>
    <% else %>
      <%= render 'deals/review', deal: exchange, review: @review %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/deals/_complete.html.erb
      <%= simple_form_for(deal, url: complete_deal_path(deal), method: :patch) do |f| %>
        <div class="text-center">
          <%= f.button :submit, "Trueque concluido", class: 'btn btn-primary-dark border-primary-darker my-2' %>
        </div>
      <% end %>

app/views/deals/_deal.html.erb
<div class="col-md-6">
  <%= simple_form_for(@deal) do |f| %>
  <%= f.hidden_field :offer_id, value: offer.id %>
  <div class="text-center">
    <%= f.button :submit, "Aceptar Oferta", class: 'btn btn-primary-dark border-primary-darker my-2' %>
  </div>
  <% end %>
</div>

app/views/deals/_reject_offer.html.erb
<%= simple_form_for(offer, url: reject_offer_path(offer), method: :patch) do |f| %>
        <%= f.button :submit, "Rechazar", class: 'btn btn-danger my-2' %>
<% end %>

app/views/deals/_review.html.erb
<div class="mt-3 container text-center p-0" data-controller="toggle-review">
  <% prev_review = Review.find_by(deal_id: deal.id, user_reviewer: current_user) %>

  <% if prev_review.nil? %>
    <button id="show-review-form" class="btn btn-primary-light m-0 p-0" data-action="click->toggle-review#showreview">Deja una reseña</button>
  <% else %>
    <p class='text-primary'><strong>Gracias por dejar tu reseña</strong></p>
  <% end %>
    <div class="row justify-content-center mt-4">
      <div class="col-md-6 review-form-container d-none" data-toggle-review-target="review">
        <%= simple_form_for(@review, url: deal_reviews_path(deal), method: :post) do |f| %>
          <%= f.input :content, as: :text, label: false, placeholder: 'Contenido de la reseña', class: 'form-control' %>
          <%= f.input :rating, as: :select, collection: 1..5, label: false, prompt: 'Calificación', class: 'form-control' %>
          <div class="text-center">
            <%= f.button :submit, "Enviar reseña", class: 'btn btn-outline-danger my-2' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/deals/_show_reviews.html.erb
<div class='d-flex justify-content-center my-4' data-controller="toggle-user-reviews">
  <% if reviewed_user == current_user %>
    <div class='' data-action='click->toggle-user-reviews#showreviews'><button class='btn btn-info p-3 my-2'>Reseñas recibidas: </button></div>
  <% else %>
    <% reviewed_name = reviewed_user.nickname.nil? ? reviewed_user.email.split("@").first : reviewed_user.nickname %>
    <div class='' data-action='click->toggle-user-reviews#showreviews'><button class='btn btn-info p-3 my-2'>Reseñas de <%= reviewed_name %>: </button></div>
  <% end %>
  <div class="col-6 col-md-4 d-none" data-toggle-user-reviews-target='reviews'>
      <% reviews.each do |review| %>
        <div class='card bg-pink p-2 m-2'>
          <% reviewer_name = review.user_reviewer.nickname.nil? ? review.user_reviewer.email.split("@").first : review.user_reviewer.nickname %>
          <p><%= reviewer_name %> dijo: </p>
          <p>Rating: <%= review.rating %> <i class="fa-solid fa-star"></i></p>
          <p>Comentario: <%= review.content %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/deals/_status.html.erb
<!-- <div class='deal-header d-flex justify-content-between bg-primary px-2 border-top'>
  <%# render 'items/chatroom', chatroom: @chatroom, user: deal.users.reject { |user| user.id == current_user.id } %>
  <p class='m-0 p-2'><%# deal.created_at.strftime("%Y-%m-%d") %></p>
</div>
-->
<%= link_to (exchange.status == 'pending' ? offer_path(exchange) : deal_path(exchange)), class: 'text-decoration-none', style: 'color: inherit;' do%>
  <div class='d-flex border bg-primary'>
    <%= render 'status_item', item: exchange.offered_item%>
    <div class="d-flex flex-column justify-content-around pb-5">
        <i id='arrow' class="fa-solid fa-arrow-right-long m-0 p-2"></i>
        <i id='arrow' class="fa-solid fa-arrow-left-long"></i>
    </div>
    <%= render 'status_item', item: exchange.requested_item%>
    </div>
<% end %>

app/views/deals/_status_item.html.erb
    <div class="w-50 d-flex justify-content-center pt-2 px-4">
      <div>
      <div class="position-relative text-white" style="width: fit-content;">
        <% if item.photos.attached? %>
          <%= cl_image_tag item.photos.first.key, class: "img-fluid rounded-4 m-auto" %>
        <% end %>
        <div class="position-absolute bottom-0 text-center rounded-bottom-4 start-0 w-100" style="background-color: rgba(0, 0, 0, 0.4);">
          <%if !item.user.nickname.nil?%>
            <p><%= item.user.nickname %></p>
          <%else%>
            <p><%= item.user.email.split("@").first %></p>
          <%end%>
        </div>
      </div>
      <p class="title-fixed-height"><%= item.name %></p>
      </div>
    </div>

app/views/deals/index.html.erb
<% if @errors %>
  <% @errors.each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error %>
    </div>
  <% end %>
<% end %>
<div class="container mt-4">
  <div class="align-items-center mb-4">
    <h2>Trueques</h2>
    <div class="d-flex justify-content-center">
      <div style="width: fit-content;" class="all-cards d-flex gap-3 flex-wrap" style="width: 80vw;">
      <%= render 'cards', exchanges: @accepted_deals %>
      <%= render 'cards', exchanges: @received_offers %>
      <%= render 'cards', exchanges: @offered_offers %>
      </div>
    </div>
    <div data-controller='display'>
      <span>Historial (<%=@completed_deals.size + @canceled_deals.size%>):</span>
      <i class="fa-solid fa-circle-chevron-up" data-action='click->display#display' data-display-target='togglebtn'></i>
      <div class='d-none my-2 d-flex flex-wrap gap-3 w-100 justify-content-center' data-display-target='info'>
        <%= render 'cards', exchanges: @finished_deals %>
      </div>
    </div>
  </div>
</div>

app/views/deals/show.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-md-7 d-flex bg-primary p-0">
    <% if @deal.offered_item.photos.attached? %>
      <%= cl_image_tag @deal.offered_item.photos.first.key, id: "offered-img-deal", class: "d-block w-100 img-fluid m-0 p-0" %>
    <% end %>
    <% if @deal.requested_item.photos.attached? %>
      <%= cl_image_tag @deal.requested_item.photos.first.key,  id: "requested-img-deal", class: "d-block w-100 img-fluid m-0 p-0" %>
    <% end %>
  </div>
  <div class="col-12 col-md-7 bg-primary">
    <p class="text-end"><i class="fa-solid fa-location-dot mx-2"></i><%= @deal.user_offerer.address %></p>
    <% reviewed_user_name = @reviewed_user.nickname.nil? ? @reviewed_user.email.split('@').first : @reviewed_user.nickname %>
    <p class="text-end"><strong>Rating de <%= reviewed_user_name %>: <%= @rating.nil? ? 'Sin reseñas' : @rating %> <i class="fa-solid fa-star"></i> </strong></p>
    <div class="bg-pink p-3 m-3">
      <%offerer_name = @deal.user_offerer.nickname.nil? ? @deal.user_offerer.email.split("@").first : @deal.user_offerer.nickname %>
      <span><%= offerer_name %> ofrece <%= @deal.offered_item.name %></span>
      <br>
      <%user_requested_name = @deal.user_requested.nickname.nil? ? @deal.user_requested.email.split("@").first : @deal.user_requested.nickname %>
      <span><%= user_requested_name %> ofrece <%= @deal.requested_item.name %></span>
    </div>

    <div class="d-flex justify-content-around align-items-center">
      <%  if @deal.status == 'accepted' %>
        <%= render 'deals/cancel', deal: @deal, class: 'btn btn-danger btn-sm'%>
      <% end %>
      <%= link_to 'Ver Perfil', user_path(@deal.users.reject { |user| user.id == current_user.id }), class: 'btn btn-light btn-sm' %>
      <%= render 'items/chatroom', chatroom: @chatroom, user: @deal.users.reject { |user| user.id == current_user.id }, class: 'btn btn-light btn-sm' %>
    </div>
    <% if @deal.status == 'completed' %>
      <%= render 'deals/review', deal: @deal, review: @review %>
    <% end %>
  </div>
</div>