config/routes.rb
Rails.application.routes.draw do
  post "/create_user", to: "users#create", as: "create_user"

  devise_for :users
  root to: "pages#home"
  get 'pages/terminos_de_uso', to: "pages#terminos_de_uso", as: "terminos_de_uso"
  get 'users/:id', to: 'users#show', as: :user
  get 'profile', to: 'users#profile', as: :profile
  resources :items, except: [:destroy] do
    member do
      patch :hide
    end
  end
  get 'myitems', to: 'items#my_items', as: :myitems

    resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
end
  resources :offers, only: [:new, :show, :create, :edit, :update, :destroy] do
    member do
      patch :reject
      patch :cancel
    end
  end
  resources :deals, only: [:index, :show, :create] do
    member do
      patch :cancel
      patch :complete
    end
    resources :reviews, only: [:create]

  end
  resources :chatrooms, only: [:index, :show, :create] do
    resources :messages, only: :create
  end
  resources :preferences, only: [:create, :destroy]

  # resources :users, only: [:create]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category

  # Specify the reverse associations for offers
  has_many :requested_offers, class_name: 'Offer', foreign_key: 'requested_item_id'
  has_many :offered_offers, class_name: 'Offer', foreign_key: 'offered_item_id'
  has_many :offered_items, through: :offered_offers, source: :requested_item
  


  validates :name, :description, :address, presence: true
  has_many_attached :photos
  has_many :preferences

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: [:name, :description, :address],
    using: {
      tsearch: { prefix: true }
    }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  scope :by_category, ->(category_id) { where(category_id: category_id) }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  # Pundit: allow-list approach
  #after_action :verify_authorized, except: :index, unless: :skip_pundit?
  #after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  before_action :set_item, only: %i[show edit update hide]

  def index
    @items = Item.where.not(user: current_user).where(hidden: false)
    @user_prefered_items = user_prefered_items
    @user_recommendations = items_within_user_preferered_categories

    @search_performed = params[:query].present? || params[:location].present? || params[:category].present?

    if params[:query].present? && params[:location].present?
      @items = Item.search_by_name_and_description(params[:query])
      @items = @items.near(params[:location], 20)
    elsif params[:query].present?
      @items = Item.search_by_name_and_description(params[:query])
    elsif params[:location].present?
      @items = Item.near(params[:location], 20)
      @user_prefered_items = @user_prefered_items.select { |item| item.address.downcase.include?(params[:location].downcase) || item.description.downcase.include?(params[:location].downcase) }
    elsif params[:category].present?
      @items = Item.by_category(params[:category])
    end
  end

  def my_items
    @items = current_user.items.where(hidden: false)
  end

  # Flat.near([40.71, 100.23], 20) # flats within 20 km of a point

  def show
    @reviewed_user = @item.user
    @reviews = Review.where(user_reviewed: @reviewed_user)
    @rating = @reviews.average(:rating).round(2) if @reviews.any?

    @deal = Deal.new
    @offer = Offer.new
    @chatroom = Chatroom.new

  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def new
    @item = Item.new
  end

  def my_items
    @items = current_user.items.where(hidden: false)
  end

  def edit
  end

  def update
    if @item.update(item_params[:photos] == [""] ? item_params.except(:photos) : item_params)
      redirect_to item_path(@item), status: :see_other
    else
      render show.html.erb, status: :unprocessable_entity
    end
  end

  def hide
    @deals = Deal.where(status: "accepted")
    @my_deals = @deals.select { |deal| deal.user_offerer == current_user || deal.user_requested == current_user }
    @deal_with_item = @my_deals.select { |deal| deal.requested_item == @item || deal.offered_item == @item }
    if @deal_with_item.any?
      redirect_to profile_path_path, status: :see_other, notice: 'No puede eliminarse un producto con trueques pendientes'
    else
      @item.update(hidden: true)
      Offer.where(offered_item: @item).update_all(status: "canceled")
      Offer.where(requested_item: @item).update_all(status: "canceled")
      redirect_to profile_path, status: :see_other, notice: 'Producto y ofertas relacionadas canceladas'
    end
  end

  private

  def item_params
    params.require(:item).permit(:category_id, :name, :description, :condition, :address, photos: [])
  end

  def set_item
    @item = Item.find(params[:id])
  end

    # this methods help populate the items index page: recommended items based on preferences and previous deals


  def user_prefered_items
    if current_user && current_user.preferences.any?
      preferences = current_user.preferences
      prefered_categories = []
      preferences.each do |preference|
        prefered_categories << preference.category
      end
      items = Item.where(category: prefered_categories).where.not(user: current_user).where(hidden: false)
      shuffled_items = items.shuffle
      # Select distinct items up to a maximum of 4
      item_for_user = shuffled_items.uniq.take(4)
      return item_for_user
    end
  end

  def user_interest_items
    if current_user && current_user.deals.where.not(status: "canceled").any?
      interest_items = []
      user_completed_deals = current_user.deals.where(status: "completed")
      user_completed_deals.each do |deal|
        if deal.user_offerer == current_user
          interest_items << deal.requested_item
        else
          interest_items << deal.offered_item
        end
      end
    end
    return interest_items
  end

  def user_interested_categories
    items = user_interest_items
    interested_categories = []
    if items.present?
      items.each do |item|
        interested_categories << item.category
      end
      return interested_categories
    end
  end

  def items_within_user_preferered_categories
    prefered_categories = user_interested_categories
    items = Item.where(category: prefered_categories).where.not(user: current_user).where(hidden: false)
    shuffled_items = items.shuffle
    # Select distinct items up to a maximum of 4
    item_for_user = shuffled_items.uniq.take(4)
    return item_for_user
  end

end

app/views/items/_card.html.erb
<div class="container">
  <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-4 g-3">
    <% items.each do |item| %>
      <div class="col" style="margin-top: 50px;">
        <div class="item d-flex flex-column h-100">
          <div class="card rounded-4 shadow bg-primary-lighter position-relative" style="flex: 1;">
            <div id="carousel<%= item.id %>" class="carousel slide" data-bs-ride="carousel" style="height: 180px; overflow: hidden; position: relative;">
              <div class="carousel-inner rounded-top-4">
                <% if item.photos.attached? %>
                  <% item.photos.each_with_index do |photo, index| %>
                    <div class="carousel-item <%= 'active' if index == 0 %>">
                      <%= cl_image_tag photo.key, class: "d-block w-100 img-fluid", style: "object-fit: cover; height: 180px" %>
                      <!-- Category name at the bottom over the image -->
                      <p class="card-text font-size-12 mb-0 position-absolute bottom-0 start-0 end-0 text-center p-2" style="background-color: rgba(255, 255, 255, 0.7);"><%= item.category.name %></p>
                    </div>
                  <% end %>
                <% end %>
              </div>
              <a class="carousel-control-prev" href="#carousel<%= item.id %>" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carousel<%= item.id %>" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </a>
            </div>
            <div class="card-body d-flex flex-column" style="overflow: hidden;">
              <h3 class="card-title title-fixed-height font-size-24" style="padding: 6px; overflow: hidden; white-space: initial;">
                <%= item.name %>
              </h3>
              <p class="card-text font-size-14 mb-0"><i class="fa-solid fa-location-dot"></i> <%= item.address %>.</p>
              <div class="mt-auto text-center"> <!-- Use Bootstrap utility classes to position button at the bottom -->
                <% if item.user == current_user %>
                  <%= link_to 'Revisa tu oferta', item_path(item), class: "btn btn-primary border-primary-darker my-4 px-4 font-size-14" %>
                <% else %>
                  <%= link_to "Selecciona esta oferta", item_path(item), class: "btn btn-primary border-primary-darker my-4 px-4 font-size-14" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/_chatroom.html.erb
<span class="text-end">
        <%= form_with model: chatroom, method: :post do |f| %>
          <%= f.hidden_field :user_id, value: user[0].id%>
          <%= f.button :submit, class: 'border-0 text-secondary bg-transparent' do %>
            <%= f.button "Enviar Mensaje", class: 'btn btn-primary' %>
          <% end %>
        <% end %>
      </span>

app/views/items/_form.html.erb
<div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card rounded-3 shadow mt-3 bg-primary">
        <div class="card-body">
          <%= simple_form_for(@item) do |f| %>
            <%= f.input :name, label: 'Nombre', input_html: { class: 'form-control bg-primary-dark border-primary-darker' }%>
            <%= f.input :description, label: 'Descripción', input_html: { class: 'form-control bg-primary-dark border-primary-darker' } %>
            <%= f.input :address, label: 'Dirección', input_html: { class: 'form-control bg-primary-dark border-primary-darker' } %>
            <%= f.association :category, label: 'Categoría', input_html: { class: 'form-select bg-primary-dark border-primary-darker' } %>
            <%= f.input :condition, as: :select, collection: ["excelente", "bueno", "regular", "aceptable"], label: 'Condición', input_html: { class: 'form-select bg-primary-dark border-primary-darker' } %>
            <%= f.input :photos, as: :file, input_html: { multiple: true, class: 'form-control bg-primary-dark border-primary-darker' }, label: 'Fotos' %>
            <%= f.button :submit, @item.persisted? ? 'Actualizar' : 'Crear', class: 'd-block w-50 m-auto btn btn-secondary-light border-primary-dark my-2' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/items/_my_items.html.erb
<% if items.present? %>
    <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-4 g-3">
      <% items.each do |item| %>
        <div class="col" style="margin-top: 50px;">
          <div class="item d-flex flex-column h-100">
            <div class="card rounded-4 shadow bg-primary-lighter position-relative" style="flex: 1;">
              <div id="carousel<%= item.id %>" class="carousel slide" data-bs-ride="carousel" style="height: 180px; overflow: hidden; position: relative;">
                <div class="carousel-inner rounded-top-4">
                  <% if item.photos.attached? %>
                    <% item.photos.each_with_index do |photo, index| %>
                      <div class="carousel-item <%= 'active' if index == 0 %>">
                        <%= cl_image_tag photo.key, class: "d-block w-100 img-fluid", style: "object-fit: cover; height: 180px" %>
                        <p class="card-text font-size-12 mb-0 position-absolute bottom-0 start-0 end-0 text-center p-2" style="background-color: rgba(255, 255, 255, 0.7);"><%= item.category.name %></p>
                      </div>
                    <% end %>
                  <% end %>
                </div>
                <a class="carousel-control-prev" href="#carousel<%= item.id %>" role="button" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carousel<%= item.id %>" role="button" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </a>
              </div>
              <div class="card-body d-flex flex-column" style="overflow: hidden;">
                <h3 class="card-title title-fixed-height font-size-24" style="padding: 6px; overflow: hidden; white-space: initial;">
                  <%= item.name %>
                </h3>
                <p class="card-text font-size-14 mb-0"><i class="fa-solid fa-location-dot"></i> <%= item.address %>.</p>
                <div class="mt-auto text-center">
                  <%= link_to(item.user == current_user ? 'Revisa tu oferta' : 'Selecciona esta oferta', item_path(item), class: "btn btn-primary border-primary-darker my-4 px-4 font-size-14") %>
                </div>
                <% if item.user == current_user %>
                  <%= form_with(model: item, url: hide_item_path(item), method: :patch, class: "d-inline text-end") do |form| %>
                    <%= form.button type: "submit", class: "btn btn-sm", data: { turbo_confirm: "¿Estás seguro?" } do %>
                      <i class="fas fa-trash"></i>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
<% end %>

app/views/items/_offer.html.erb
<%# This partial is used to create a new offer for a specific item %>
<%# requested_item is what the users access in the index and show %>
<%# offered_item is what the person that wants an exchange offers %>
<div class="col-md-6">
  <%= simple_form_for(@offer, url: offers_path, method: :post) do |f| %>
    <div class="form-group">
      <%= f.label :offered_item_id, "Ofrece un producto" %>
      <%= f.select :offered_item_id, options_for_select(current_user.items.pluck(:name, :id)), { prompt: "..." }, class: 'form-control' %>
    </div>
    <div class="text-center">
        <%= f.button :submit, "Enviar Oferta", class: 'btn btn-book my-2' %>
    </div>
  <% end %>
</div>

app/views/items/_preferences.html.erb
<div class="container my-3">
  <h3>Basado en tus Preferencias</h3>
  <%= render "card", items: user_prefered_items %>
</div>
<br>
<br>

app/views/items/_recommendations.html.erb
<br>
<br>
<div class="container mt-3">
  <h3>Basado en tus trueques previos</h3>
  <%= render "card", items: user_recommendations %>
</div>
<br>

app/views/items/index.html.erb
<div class="mobile-only w-75 m-auto">
  <%= render 'shared/search'%>
</div>

<%= render 'shared/banner'%>
<br>
<% if @search_performed && @items.any? %>
  <div class='container'>
    <h3>Resultados de la búsqueda</h3>
    <%= render "card", items: @items %>
  </div>
<% elsif @search_performed %>
  <div class='container'>
    <p>No hay resultados</p>
  </div>
<% else %>
  <% if @user_recommendations.present? %>
    <div class='container'>
      <%= render 'items/recommendations', user_recommendations: @user_recommendations %>
    </div>
  <% end %>

  <% if @user_prefered_items.present? %>
    <div class='container'>
      <%= render 'items/preferences', user_prefered_items: @user_prefered_items %>
    </div>
  <% end %>

  <div class='container'>
    <h3>Ofertas</h3>
    <% if @items.empty? %>
      <h3>No hay ofertas disponibles</h3>
    <% else %>
      <%= render "card", items: @items %>
    <% end %>
  </div>
<% end %>

app/views/items/my_items.html.erb
<div class='container'>
  <h1>Mis Productos</h1>
  <%= link_to "Agregar Producto", new_item_path, class: "btn btn-primary-dark border-primary-darker" %>
  <%= render 'my_items', items: @items %>
</div>

app/views/items/new.html.erb
<h1 class='text-center my-3'>Nuevo producto</h1>
<%= render "form", item: @item %>

app/views/items/show.html.erb
<div class="container-fluid w-75" data-controller="toggle" style="margin-top: 50px">
  <div class="row">
    <div class="col-md-6 order-md-1 order-2">
      <div class="container my-3">
        <h2><%= @item.name %></h2>
        <h5><%= @item.user.nickname %></h5>
        <div style="display: inline;">
          <p>Rating: <strong><%= @rating.nil? ? 'Sin reseñas' : @rating %> <i class="fa-solid fa-star"></i></strong></p>
        </div>
        <h5><i class="fa-solid fa-location-dot pe-2"></i><%= @item.user.address %></h5>
        <p class="card-text"> <%= @item.description %>.</p>
        <p class="mb-2">Cambio por: </p>
        <div class="d-flex justify-content-start flex-wrap gap-3 mb-5" style="overflow-x: auto;">
          <% @item.user.preferences.each do |preference|%>
            <div class="badge bg-secondary rounded-5 ">
              <%= preference.category.name %>
            </div>
          <% end %>
        </div>


      </div>
    </div>
    <div class="col-md-6 order-md-2 order-1">
      <div id="carousel<%= @item.id %>" class="carousel slide position-relative" data-bs-ride="carousel" style="height: 300px; width: 100%; overflow: hidden;">
        <div class="carousel-inner">
          <% if @item.photos.attached? %>
            <% @item.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%= "active" if index == 0 %> position-relative">
                <div class="d-flex justify-content-center align-items-center">
                  <%= cl_image_tag photo.key, class: "d-block mx-auto", style: "height: 300px" %>
                  <span class="badge bg-dark position-absolute bottom-0 ">
                    <%= @item.category.name %>
                  </span>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
        <!-- Carousel controls -->
        <a class="carousel-control-prev" href="#carousel<%= @item.id %>" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel<%= @item.id %>" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </a>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center align-items-center mt-5">
    <div class="d-flex gap-2">
      <% if @item.user == current_user %>
        <button class='btn btn-secondary' data-action='click->toggle#showoffer'>Edita tu producto</button>
      <% else %>
        <div><button class='btn btn-secondary' data-action='click->toggle#showoffer'>Me interesa!</button></div>
        <%= form_with model: @chatroom, method: :post do |f| %>
          <%= f.hidden_field :user_id, value: @item.user.id%>
          <%= f.button "Enviar Mensaje", class: 'btn btn-primary' %>
        <% end %>
        <%= link_to 'Ver Perfil', user_path(@item.user), class: 'btn btn-light' %>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center d-none m-3" data-toggle-target='form'>
    <% if @item.user == current_user %>
      <%= render 'form' %>
    <% else %>
      <%= render 'offers/form' %>
    <% end %>
  </div>

</div>