config/routes.rb
Rails.application.routes.draw do
  post "/create_user", to: "users#create", as: "create_user"

  devise_for :users
  root to: "pages#home"
  get 'pages/terminos_de_uso', to: "pages#terminos_de_uso", as: "terminos_de_uso"
  get 'users/:id', to: 'users#show', as: :user
  get 'profile', to: 'users#profile', as: :profile
  resources :items, except: [:destroy] do
    member do
      patch :hide
    end
  end
  get 'myitems', to: 'items#my_items', as: :myitems

    resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
end
  resources :offers, only: [:new, :show, :create, :edit, :update, :destroy] do
    member do
      patch :reject
      patch :cancel
    end
  end
  resources :deals, only: [:index, :show, :create] do
    member do
      patch :cancel
      patch :complete
    end
    resources :reviews, only: [:create]

  end
  resources :chatrooms, only: [:index, :show, :create] do
    resources :messages, only: :create
  end
  resources :preferences, only: [:create, :destroy]

  # resources :users, only: [:create]
end

app/views/shared/navbar/_avatar.html.erb
        <i class="fas fa-bars avatar dropdown" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
        <div class="dropdown-menu dropdown-menu-end position-absolute" aria-labelledby="navbarDropdown">

          <% if user_signed_in? %>
            <%= link_to "Perfil", profile_path, class: "dropdown-item" %>
            <% if Message.where.not(user: current_user).where(read: false, chatroom: current_user.chatrooms).any? %>
              <%= link_to chatrooms_path, class: "dropdown-item desktop-only" do %>
                Inbox <i class="fa-regular fa-envelope"></i>
              <% end %>
            <% else %>
              <%= link_to chatrooms_path, class: "dropdown-item desktop-only" do %>
                Inbox <i class="fa-solid fa-envelope-open"></i>
              <% end %>
            <% end %>
            <%= link_to "Nuevo producto", new_item_path, class: "dropdown-item desktop-only" %>
            <%= link_to "Mis productos", myitems_path, class: "dropdown-item desktop-only" %>
            <% if current_user.received_offers.where(status: 'pending').empty? %>
              <%= link_to "Mis trueques", deals_path, class: "dropdown-item desktop-only" %>
            <% else %>
              <%= link_to deals_path, class: "dropdown-item desktop-only" do %>
                Mis trueques <i class="fa-solid fa-bell"></i>
              <% end %>
            <% end %>

            <%= link_to "Log out", "/users/sign_out", class: "dropdown-item", data: {turbo_method: :delete} %>
          <% else %>
            <%= link_to "Log in", "/users/sign_in", class: "dropdown-item" %>
            <%= link_to "Sign up", "/users/sign_up", class: "dropdown-item" %>
          <% end %>
        </div>